import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>about</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>

      <div>nice</div>
    </>
  );
};

export default Home;
