import Head from "next/head";
import Link from "next/link";

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Tour de Orava</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <div className="space-y-16 mt-5">
        {[2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021]
          .reverse()
          .map((rocnik) => (
            <div key={rocnik} className="text-center">
              <h2 className="text-6xl hidden">{rocnik}</h2>
              <img
                src={`/index/header${rocnik}.jpg`}
                alt={`Ročník ${rocnik}`}
                className="w-full"
              ></img>
            </div>
          ))}
      </div>
    </>
  );
}
