import Head from "next/head";
import Link from "next/link";

export default function HomePage({ posts }) {
  return (
    <>
      <Head>
        <title>Tour de Orava</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <div className="mt-6 mx-auto">
        <ul className="block space-y-12">
          {posts?.map((post) => (
            <li key={post.slug}>
              <figure className="alignwide wp-block-post-featured-image">
                <Link href={`/rocnik/${post.slug}`}>
                  <a>
                    <img
                      width="798"
                      height="198"
                      src={post.featuredImage.node.sourceUrl}
                      srcSet={post.featuredImage.node.srcSet}
                      sizes={post.featuredImage.node.sizes}
                      className="attachment-post-thumbnail size-post-thumbnail wp-post-image"
                      alt={post.slug}
                      loading="lazy"
                    />
                  </a>
                </Link>
              </figure>
            </li>
          ))}
        </ul>
      </div>
    </>
  );
}
